[build]
  publish = "TraceNet_Frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

# Disable Netlify's injected attribution badge
[build.environment]
  NETLIFY_NO_BADGE = "true"
